### ISSUE TITLE
The current .NET SDK does not support targeting .NET Core 2.2

### ISSUE THREAD

**Issue by SaeedAkhter-MSFT** [Azure-Samples/active-directory-dotnetcore-devicecodeflow-v2#11]
I have Visual Studio Commnity 2017 latest installed, 
	Microsoft Visual Studio Community 2017 
	Version 15.9.11
	VisualStudio.15.Release/15.9.11+28307.586
	Microsoft .NET Framework
	Version 4.7.03190

When I attempt to build I'm getting an error that I did not have .NET Core 2.2 installed:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.	device-code-flow-console	C:\Program Files\dotnet\sdk\2.1.505\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	137	

Double check what sdks I had, and sure enough .NET Core 2.2 isn't there:

C:\Users\saeeda>dotnet --list-sdks
2.1.401 [C:\Program Files\dotnet\sdk]
2.1.505 [C:\Program Files\dotnet\sdk]

Found the download page for .NET Core here:

https://dotnet.microsoft.com/download/dotnet-core/2.2

Ran the .NET Core installer for 2.2.203 (which is the latest as of the time of writing this)  Output of the installer:
    The following were installed at C:\Program Files\dotnet
    • .NET Core SDK 2.2.203
    • .NET Core Runtime 2.2.4
    • ASP.NET Core Runtime 2.2.4

C:\Users\saeeda>dotnet --list-sdks
2.1.401 [C:\Program Files\dotnet\sdk]
2.1.505 [C:\Program Files\dotnet\sdk]
2.2.203 [C:\Program Files\dotnet\sdk]

Run the sample again same error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.	device-code-flow-console	C:\Program Files\dotnet\sdk\2.1.505\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	137	

Found another link, this one appears to have a chart showing which .NET Core is needed for which Visual Studio, it says to install v2.2.106 for VS 2019

https://dotnet.microsoft.com/download/visual-studio-sdks

Ran the installer for 2.2.106, output:
    The following were installed at C:\Program Files\dotnet
    • .NET Core SDK 2.2.106
    • .NET Core Runtime 2.2.4
    • ASP.NET Core Runtime 2.2.4

Finally I was able to build and run.

I was able to figure it out, but I wasted 20mins searching for the right SDK to install.  Let's add a step in the pre-requisites with a link to the .NET Core SDK to install?

**Comment by jmprieur** [comment]
@SaeedAkhter-MSFT we have added precisions to the README.md
however, normally if VS is up to date, it downloads the SDKs for you (so I'm a bit interested to understand why it did not)
