### ISSUE TITLE
This sample will not work with a Microsoft account

### ISSUE THREAD

**Issue by PankajBhojwani** [Azure-Samples/active-directory-dotnetcore-devicecodeflow-v2#15]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Log in with a Microsoft account

### Any log messages given by the failure
> AADSTS500201: We are unable to issue tokens from this API version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.

### Expected/desired behavior
> Successful login

### OS and Version?
> Windows 10

### Versions
> Windows 10

### Mention any other details that might be useful
> I know the readme/writeup says that this sample will not work with a Microsoft account. Is there anything I can do to make this work with a Microsoft account? 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
You are right @PankajBhojwani : the Microsoft Identity Platform (formerly named Azure AD v2.0) does not yet support Personal Microsoft accounts. Development is, however in progress service side. As soon as it is available, MSAL.NET will allow it, and the sample will work with MSAS. 
See http://aka.ms/msal-net-device-code-flow and in particular the [Constraints](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Device-Code-Flow#constraints) section

BTW, the instructions in the README.md only propose you to use any organization.
https://github.com/Azure-Samples/active-directory-dotnetcore-devicecodeflow-v2#register-the-client-app-active-directory-dotnet-deviceprofile

**Comment by PankajBhojwani** [comment]
According to this documentation https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-endpoint-comparison, the Microsoft Identity Platform does support Personal Microsoft accounts. So I suppose one of the links is outdated?

**Comment by jmprieur** [comment]
Thanks for your feedback, @PankajBhojwani 
The comparison article is a bit high level, but then the more detailed article mentions that personal accounts are not yet supported for Device code flow.
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-app-registration#audience-for-desktop-app-silent-flows

I'll raise an issue to update the comparison artic;e

**Comment by PankajBhojwani** [comment]
Thank you!

Though I must say I am still a little confused, some time ago I found this repo - https://github.com/yangl900/azshell - which basically lets you access the Azure cloud shell from the command line. To handle authentication to your Azure cloud shell, it uses Device code flow and I have used it to authenticate my personal account - do you have any idea why this app is able to perform the authentication then?

**Comment by jmprieur** [comment]
@PankajBhojwani 
In AAD v1.0 common was what is today organizations in the Microsoft Identity Platform (formerly named AAD v2.0). See https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration#signification-of-the-common-authority

The reason why you were able to login with your personal account with azshell is probably because your personal account was a [guest account](https://docs.microsoft.com/en-us/azure/active-directory/b2b/what-is-b2b) in the tenant used to connect azshell to the cloud

**Comment by PankajBhojwani** [comment]
Okay thank you so much! Just for clarity, does that mean that azshell is using AAD v1.0?

**Comment by jmprieur** [comment]
Yes, looking at the code, it seems so 
https://github.com/yangl900/azshell/search?q=activeDirectoryEndpoint&unscoped_q=activeDirectoryEndpoint

**Comment by PankajBhojwani** [comment]
Thank you!

**Comment by PankajBhojwani** [comment]
@jmprieur 
Just so I am completely clear on the situation -

> The reason why you were able to login with your personal account with azshell is probably because your personal account was a guest account in the tenant used to connect azshell to the cloud

So because my personal account is a guest account, I can use device code flow with the Azure AD v1.0 endpoint (even though v1.0 technically does not support personal accounts). 

I am wondering why my 'guest account status' does not transfer over to device code flow when using the Microsoft Identity Platform endpoint. Is device code flow with guest accounts also not yet supported by Microsoft Identity Platform?

**Comment by jmprieur** [comment]
> So because my personal account is a guest account, I can use device code flow with the Azure AD v1.0 endpoint (even though v1.0 technically does not support personal accounts).

Only in single-tenant applications (using a tenanted authority, not common). This should also work with the Microsoft Identity Platform endpoint?

**Comment by PankajBhojwani** [comment]
Interesting, so that brings me back to this sample here. I can't seem to use my guest account to log in (the same account I used to successfully log in when running azshell). Is this not a single-tenant application then?

**Comment by jennyf19** [comment]
@PankajBhojwani this is working now w/the MSAL 4.5 release.
