### ISSUE TITLE
MSA Support

### ISSUE THREAD

**Issue by lanatmwan** [Azure-Samples/active-directory-dotnetcore-devicecodeflow-v2#2]
I am interested in this scenario for accessing my personal OneDrive through the Graph. This is the closest method I have seen to working for .net core. Are there plans to make this work with MSA as well? What about providing an api function that takes a username and password so that information can be read in any manner desired by the developer?

**Comment by jmprieur** [comment]
@lanatmwan : Device code flow is coming to MSA as well (in the coming months: we are working on adding its support in the Azure AD service)

There is also a Username/Password flow: See [doc](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Username-Password-Authentication) and the sample: [active-directory-dotnetcore-console-up-v2](https://github.com/Azure-Samples/active-directory-dotnetcore-console-up-v2), however, MSA does not accept username/passwords (for security reasons)

Feel free to close this issue if you are satisfied by the answer.

**Comment by lanatmwan** [comment]
"Device code flow is coming to MSA as well"
Good to hear. FWIW my main interest is in working with my MS Graph data from Powershell 6 which is based off of .net core. The typical authentication where a minimal browser is brought up with a login  prompt doesn't work because core doesn't have a browser. I know that .net core3 is slated to get a browser experience so I am hoping that auth experience gets fixed relatively soon too. For now, I am able to do it with powershell v5 so I'm not blocked at least. 

"MSA does not accept username/passwords (for security reasons)"
Maybe not the best venue but why is supplying a user/pass any less secure than me doing it via a browser that lets me do the same thing? Its slightly more tedious, but I can automate browser interactions with Selenium and access my data with just my user/pass, and I want to do the same with a script.

**Comment by jmprieur** [comment]
@lanatmwan : 
I'm not aware of .NET core providing a web browser control. My understanding (but I could be wrong) is that the .NET Core team will provide Microsoft extension libraries for Windows.Forms and WPF, on the Windows platform. I never read that this would be portable. If .NET Core 3.0 provides a portable solution for a Web browser, we'll add it to [MSAL.NET](6.	https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki#conceptual-documentation) which is where all the innovation will go moving forward

MSA users can very well have setup multi-factor authentication, and MSA verifies a number of conditions (you might have noticed that when you travel to another country, it sometimes asks you to prove that this is you). All that requires user interaction through a web browser. If you automate the browser interaction, in theory you would have to automate all these cases.

**Comment by lanatmwan** [comment]
I apparently read a lot of wishful thinking into a blog post about upcoming releases of .net. Core is indeed getting forms and wpf as extensions but the updated browser control is for .net framework 4.8 only.
