### ISSUE TITLE
How to configure the service app (not .net core, but .net 4.7 framework)? 

### ISSUE THREAD

**Issue by oblomingo** [Azure-Samples/active-directory-dotnetcore-devicecodeflow-v2#34]
> In my current project I have the case very familiar that you have implemented in this repository, but in my case service application (TodoList-webAPI) should be implemented using .Net framework 4.7. I understand, that it's not really related to your implementation, but still could you please help me with that?   
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1). Run 2-Call-OwnApi Configure.ps1
2). Grant admin consent.
3). Run applications (Daemon-Console and origin TodoList-WebAPI) and ensure that the solution works perfectly.
4). Add a new TodoList-Web app based on ASP.NET project (4.7 .NET Framework) to the solution.
5). Add AAD configuration code:
```
public void ConfigureAuth(IAppBuilder app)
{
    app.UseWindowsAzureActiveDirectoryBearerAuthentication(
        new WindowsAzureActiveDirectoryBearerAuthenticationOptions
        {
            Tenant = ConfigurationManager.AppSettings["ida:Tenant"],
            TokenValidationParameters = new TokenValidationParameters
            {
                ValidAudience = ConfigurationManager.AppSettings["ida:Audience"]
            },
        });
}
```
6). Add to web.config:
```
    <add key="ida:Tenant" value="<tenantName>.onmicrosoft.com" />
    <add key="ida:Audience" value="<service app Application ID URI>" />
    <add key="ida:ClientID" value="<service app Application (client) ID>" />
```
7). Change original TodoList-WebApi url port to another.
8). Change new TodoList-Web url port to correct.
9). Run applications (Daemon-Console and new TodoList-Web) doesn't work. 

### Any log messages given by the failure
Error message in the console app:
Failed to call the Web Api: Unauthorized
Content: {"Message":"Authorization has been denied for this request."}

### Expected/desired behavior
Daemon-Console and new TodoList-Web works, console app shows items from new TodoList-Web app.

### OS and Version?
> Windows 10
### Versions
>Visual Studio 2019, Version 16.4.5

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment]
When the daemon app acquires an access token for the API, the **aud** claim will be `"aud": "api://<service-app-id>"`. 
While the NetFramework API, by default has the web,config key for audience as: `https://<your-tenant-domain>/<web-api-name>`.

So, your API is expecting an audience which is not the one present in the access token. If you change the **ida:Audience** to `api://<service-app-id>` it will work.

Let me know if you need more help, or if I can close the issue.

Thanks

**Comment by oblomingo** [comment]
Thank you for the clarification.
I have checked new TodoList-Web (.Net 4.7) application settings and found that audinece has correct value. Here my settings:
```
<configuration>
  <appSettings>
	...
    <add key="ida:Tenant" value="tenant4testing.onmicrosoft.com" />
    <add key="ida:Audience" value="api://05eb14f4-1cb7-4269-890f-#########" />
    <add key="ida:ClientID" value="05eb14f4-1cb7-4269-890f-#########" />
  </appSettings>
```
ida:Audience value copied from tenant4testing.onmicrosoft.com/App Registrations/TodoList-webapi-daemon-v2/Application ID URI.
ida:ClientID value copied from tenant4testing.onmicrosoft.com/App Registrations/TodoList-webapi-daemon-v2/Application (client) ID.
My Startup.cs file:
```
using Microsoft.IdentityModel.Tokens;
using Microsoft.Owin.Security.ActiveDirectory;
using Owin;
using System.Configuration;

namespace TestApp
{
    public partial class Startup
    {
        public void ConfigureAuth(IAppBuilder app)
        {
            app.UseWindowsAzureActiveDirectoryBearerAuthentication(
                new WindowsAzureActiveDirectoryBearerAuthenticationOptions
                {
                    Tenant = ConfigurationManager.AppSettings["ida:Tenant"],
                    TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidAudience = ConfigurationManager.AppSettings["ida:Audience"]
                    },
                });
        }
    }
}
```
Daemon-Console witn origin TodoList-WebAPI (.Net Core) works perfectly, but with new TodoList-Web (.Net 4.7) still doesn't work. By the way, Startup file uses only ida:Tenant and ida:Audience, does it mean that I dont need ida:ClientID value in my web.config?

**Comment by jmprieur** [comment]
@oblomingo. I'm a bit confused as you mention starting from a daemon app (this sample), but ask the question in the device code flow sample (this sample), and this is really about a console app calling a Web API.

I suggest you have a look at this [Web API incremental tutorial](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2) as well as this [Protected web api](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-overview) scenario landing page for Web APIs.

**Comment by TiagoBrenck** [comment]
@oblomingo if you still have questions, would you mind opening the issue to its appropriate sample repo? 

About policies, it got introduced on .NET Core, so you would have to find another strategy to replace its usage. Maybe a filter could do the job?

I have tested on my end having a .NET Framework API and it worked. I used the code the VS generated for me as is. If you added custom code, I would suggest double checking them.

If you want to continue this discussion, please lets do it on the correct sample repo. Thanks

**Comment by jennyf19** [comment]
Going to close.
